### ISSUE TITLE
After composer require error: You have requested a non-existent service "cart.entity".

### ISSUE THREAD

**Issue by vchampanery** [mobilecart/mobilecartsubscriptionbundle#1]
hello 
   i have use >composer require mobilecart/subscriptionbundle "dev-master" for symfony2.8  and copy on services.xml to config/services.yml . but still i am getting this error
  
error
You have requested a non-existent service "cart.entity".

**Comment by mobilecart** [comment]
Hello. Here is a list of instructions for installing the core package of Mobile Cart. Ensure that you are enabling MobileCartCoreBundle() before the other MobileCart* packages in app/AppKernel.php, and you will not receive the error. 

https://packagist.org/packages/mobilecart/corebundle
